// AUTO-GENERATED by Supabase MCP: Types for your database
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      documents: {
        Row: {
          file_name: string | null;
          file_url: string | null;
          id: string;
          tax_return_id: string | null;
          uploaded_at: string | null;
          uploader_id: string | null;
        };
        Insert: {
          file_name?: string | null;
          file_url?: string | null;
          id?: string;
          tax_return_id?: string | null;
          uploaded_at?: string | null;
          uploader_id?: string | null;
        };
        Update: {
          file_name?: string | null;
          file_url?: string | null;
          id?: string;
          tax_return_id?: string | null;
          uploaded_at?: string | null;
          uploader_id?: string | null;
        };
      };
      messages: {
        Row: {
          content: string;
          created_at: string | null;
          id: string;
          read: boolean | null;
          recipient_id: string | null;
          sender_id: string | null;
        };
        Insert: {
          content: string;
          created_at?: string | null;
          id?: string;
          read?: boolean | null;
          recipient_id?: string | null;
          sender_id?: string | null;
        };
        Update: {
          content?: string;
          created_at?: string | null;
          id?: string;
          read?: boolean | null;
          recipient_id?: string | null;
          sender_id?: string | null;
        };
      };
      payments: {
        Row: {
          amount: number | null;
          created_at: string | null;
          id: string;
          status: string | null;
          stripe_session_id: string | null;
          user_id: string | null;
        };
        Insert: {
          amount?: number | null;
          created_at?: string | null;
          id?: string;
          status?: string | null;
          stripe_session_id?: string | null;
          user_id?: string | null;
        };
        Update: {
          amount?: number | null;
          created_at?: string | null;
          id?: string;
          status?: string | null;
          stripe_session_id?: string | null;
          user_id?: string | null;
        };
      };
      profiles: {
        Row: {
          agent_id: string | null;
          created_at: string | null;
          email: string | null;
          full_name: string | null;
          id: string;
          phone: string | null;
          role: Database["public"]["Enums"]["role_enum"] | null;
          visa_type: string | null;
        };
        Insert: {
          agent_id?: string | null;
          created_at?: string | null;
          email?: string | null;
          full_name?: string | null;
          id?: string;
          phone?: string | null;
          role?: Database["public"]["Enums"]["role_enum"] | null;
          visa_type?: string | null;
        };
        Update: {
          agent_id?: string | null;
          created_at?: string | null;
          email?: string | null;
          full_name?: string | null;
          id?: string;
          phone?: string | null;
          role?: Database["public"]["Enums"]["role_enum"] | null;
          visa_type?: string | null;
        };
      };
      tax_returns: {
        Row: {
          client_id: string | null;
          client_name: string | null;
          created_at: string | null;
          due_date: string | null;
          id: string;
          refund_amount: number | null;
          residency_status: string | null;
          status: Database["public"]["Enums"]["tax_status_enum"] | null;
          submission_date: string | null;
          tax_payable: number | null;
          tax_year: string | null;
          timeline: Json | null;
          total_deductions: number | null;
          total_income: number | null;
          visa_type: string | null;
        };
        Insert: {
          client_id?: string | null;
          client_name?: string | null;
          created_at?: string | null;
          due_date?: string | null;
          id?: string;
          refund_amount?: number | null;
          residency_status?: string | null;
          status?: Database["public"]["Enums"]["tax_status_enum"] | null;
          submission_date?: string | null;
          tax_payable?: number | null;
          tax_year?: string | null;
          timeline?: Json | null;
          total_deductions?: number | null;
          total_income?: number | null;
          visa_type?: string | null;
        };
        Update: {
          client_id?: string | null;
          client_name?: string | null;
          created_at?: string | null;
          due_date?: string | null;
          id?: string;
          refund_amount?: number | null;
          residency_status?: string | null;
          status?: Database["public"]["Enums"]["tax_status_enum"] | null;
          submission_date?: string | null;
          tax_payable?: number | null;
          tax_year?: string | null;
          timeline?: Json | null;
          total_deductions?: number | null;
          total_income?: number | null;
          visa_type?: string | null;
        };
      };
    };
    Enums: {
      role_enum: "agent" | "client" | "admin";
      tax_status_enum: "completed" | "in-progress" | "pending";
    };
  };
};
